# Site settings
title: "PCjs: The Original IBM PC in a Browser"
email: Jeff@pcjs.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""             # "/pcjs" when using http://jeffpar.github.io/pcjs, or "" when using http://pcjs.net 
url: "http://pcjs.net"  # "http://jeffpar.github.io" or "http://pcjs.net"
twitter_username: jeffpar
github_username:  jeffpar

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

pcjs_version: 1.20.1
