# Site settings

title: "PCjs: The Virtual IBM PC"
email: Jeff@pcjs.org
description: >
  PCjs: The Original IBM PC in a Browser.
  Classic computer simulations in JavaScript.
  Includes an archive of historical PC software and publications.
  Additional computer simulations in JavaScript include the 6502-based Ohio Scientific Challenger 1P.
baseurl: ""                 # "/pcjs" when using http://jeffpar.github.io or "" when using http://www.pcjs.org 
url: "http://www.pcjs.org"  # "http://jeffpar.github.io" or "http://www.pcjs.org"
twitter_username: jeffpar
github_username:  jeffpar

left_brace: "{"
right_brace: "}"
encoding: UTF-8

# Build settings

exclude: ["**/index.html", "**/archive", "**/c64", "logs", "node_modules", "projects", "src", "**/src", "tmp", "**/tmp", "videos", "web", ".git", ".idea"]
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Custom site settings

pcjs:
  domain: pcjs.org    # whereas site.url is used for linking purposes, site.pcjs.domain is used for display purposes
  version: 1.22.1     # IMPORTANT: keep pcjs.version in sync with package.json:version
  compiled: true      # by default, the compiled pcjs.version scripts will be used (eg, pc.js or pc-dbg.js)
  pc_scripts:         # if pcjs.compiled is false, the following scripts will be included instead, in the order listed
    - /modules/shared/lib/defines.js
    - /modules/shared/lib/nodebug.js
    - /modules/shared/lib/diskapi.js
    - /modules/shared/lib/dumpapi.js
    - /modules/shared/lib/reportapi.js
    - /modules/shared/lib/userapi.js
    - /modules/shared/lib/strlib.js
    - /modules/shared/lib/usrlib.js
    - /modules/shared/lib/weblib.js
    - /modules/shared/lib/component.js
    - /modules/pcjs/lib/defines.js
    - /modules/pcjs/lib/x86.js
    - /modules/pcjs/lib/interrupts.js
    - /modules/pcjs/lib/messages.js
    - /modules/pcjs/lib/panel.js
    - /modules/pcjs/lib/bus.js
    - /modules/pcjs/lib/memory.js
    - /modules/pcjs/lib/cpu.js
    - /modules/pcjs/lib/x86seg.js
    - /modules/pcjs/lib/x86cpu.js
    - /modules/pcjs/lib/x86fpu.js
    - /modules/pcjs/lib/x86func.js
    - /modules/pcjs/lib/x86help.js
    - /modules/pcjs/lib/x86mods.js
    - /modules/pcjs/lib/x86ops.js
    - /modules/pcjs/lib/x86op0f.js
    - /modules/pcjs/lib/chipset.js
    - /modules/pcjs/lib/rom.js
    - /modules/pcjs/lib/ram.js
    - /modules/pcjs/lib/keyboard.js
    - /modules/pcjs/lib/video.js
    - /modules/pcjs/lib/parallelport.js
    - /modules/pcjs/lib/serialport.js
    - /modules/pcjs/lib/mouse.js
    - /modules/pcjs/lib/disk.js
    - /modules/pcjs/lib/fdc.js
    - /modules/pcjs/lib/hdc.js
    - /modules/pcjs/lib/debugger.js
    - /modules/pcjs/lib/state.js
    - /modules/pcjs/lib/computer.js
    - /modules/shared/lib/embed.js
    - /modules/shared/lib/save.js
  c1p_scripts:
    - /modules/shared/lib/defines.js
    - /modules/shared/lib/nodebug.js
    - /modules/shared/lib/dumpapi.js
    - /modules/shared/lib/reportapi.js
    - /modules/shared/lib/strlib.js
    - /modules/shared/lib/usrlib.js
    - /modules/shared/lib/weblib.js
    - /modules/shared/lib/component.js
    - /modules/c1pjs/lib/defines.js
    - /modules/c1pjs/lib/panel.js
    - /modules/c1pjs/lib/cpu.js
    - /modules/c1pjs/lib/rom.js
    - /modules/c1pjs/lib/ram.js
    - /modules/c1pjs/lib/keyboard.js
    - /modules/c1pjs/lib/video.js
    - /modules/c1pjs/lib/serial.js
    - /modules/c1pjs/lib/disk.js
    - /modules/c1pjs/lib/debugger.js
    - /modules/c1pjs/lib/computer.js
    - /modules/shared/lib/embed.js
  pc8080_scripts:
    - /modules/shared/lib/defines.js
    - /modules/shared/lib/dumpapi.js
    - /modules/shared/lib/reportapi.js
    - /modules/shared/lib/userapi.js
    - /modules/shared/lib/strlib.js
    - /modules/shared/lib/usrlib.js
    - /modules/shared/lib/weblib.js
    - /modules/shared/lib/component.js
    - /modules/pc8080/lib/defines.js
    - /modules/pc8080/lib/cpudef.js
    - /modules/pc8080/lib/messages.js
    - /modules/pc8080/lib/panel.js
    - /modules/pc8080/lib/bus.js
    - /modules/pc8080/lib/memory.js
    - /modules/pc8080/lib/cpu.js
    - /modules/pc8080/lib/cpusim.js
    - /modules/pc8080/lib/cpuops.js
    - /modules/pc8080/lib/chipset.js
    - /modules/pc8080/lib/rom.js
    - /modules/pc8080/lib/ram.js
    - /modules/pc8080/lib/keyboard.js
    - /modules/pc8080/lib/video.js
    - /modules/pc8080/lib/debugger.js
    - /modules/pc8080/lib/state.js
    - /modules/pc8080/lib/computer.js
    - /modules/shared/lib/embed.js
    - /modules/shared/lib/save.js
